### ISSUE TITLE
Unable to Return Book

### ISSUE THREAD

**Issue by vipranarayan14** [my-librarian/ui-core#2]
I logged in in "http://my-librarian.is-best.net" and tried to return the book but I couldn't.

I got this error in the network tab:
`{"message":"Unknown column 'receiverid' in 'field list'"}`

Snapshots:
![image](https://cloud.githubusercontent.com/assets/17687018/16728768/fedb79ba-4785-11e6-9303-4856e89e7ebd.png)

**Comment by Gopikrishna19** [comment]
Fixed
